apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metrics-test
  namespace: metrics-test
  labels:
    app: metrics-app
spec:
  selector:
    matchLabels:
      prometheus: "true"
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
